services:

  faceread-api:
    image: ddb7/faceread-api:latest
    container_name: faceread-api

    ports:
      - "8000:8000"

    restart: unless-stopped

    environment:
      - MONGO_HOST=host.docker.internal
      - MONGO_PORT=27017
      - MONGO_DB=faceread

    extra_hosts:
      - "host.docker.internal:host-gateway"

    networks:
      - faceread-network

  faceread-front:
    image: ddb7/faceread-front:latest
    container_name: faceread-front

    ports:
      - "3001:80"

    restart: unless-stopped

    depends_on:
      - faceread-api

    networks:
      - faceread-network

networks:
  faceread-network:
    external: true
